using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using TaskManagement.Api.Data;

namespace TaskManagement.Tests.Api;

public class TasksApiCrudTests : IClassFixture<TasksApiCrudTests.ApiFactory>
{
    // Guaranteed not to collide with ids auto-generated by the handful of tasks
    // created across the [Fact]s in this class (the shared in-memory DB is never reset).
    private const int NonExistentId = 999999;

    private readonly HttpClient _client;

    public TasksApiCrudTests(ApiFactory factory)
    {
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task GetAll_Returns200AndIncludesCreatedTask()
    {
        var createResponse = await _client.PostAsJsonAsync("/api/tasks", new { Title = "Write report" });
        using var created = JsonDocument.Parse(await createResponse.Content.ReadAsStringAsync());
        var createdId = created.RootElement.GetProperty("id").GetInt32();

        var response = await _client.GetAsync("/api/tasks");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);

        using var body = JsonDocument.Parse(await response.Content.ReadAsStringAsync());
        var containsCreatedTask = false;
        foreach (var task in body.RootElement.EnumerateArray())
        {
            if (task.GetProperty("id").GetInt32() == createdId)
            {
                containsCreatedTask = true;
                break;
            }
        }

        Assert.True(containsCreatedTask);
    }

    [Fact]
    public async Task GetById_NonExistentId_Returns404()
    {
        var response = await _client.GetAsync($"/api/tasks/{NonExistentId}");

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }

    [Fact]
    public async Task Put_ValidTitle_Returns204()
    {
        var createResponse = await _client.PostAsJsonAsync("/api/tasks", new { Title = "Original title" });
        using var created = JsonDocument.Parse(await createResponse.Content.ReadAsStringAsync());
        var createdId = created.RootElement.GetProperty("id").GetInt32();

        var putResponse = await _client.PutAsJsonAsync($"/api/tasks/{createdId}", new { Title = "Updated title" });

        Assert.Equal(HttpStatusCode.NoContent, putResponse.StatusCode);

        var getResponse = await _client.GetAsync($"/api/tasks/{createdId}");
        using var updated = JsonDocument.Parse(await getResponse.Content.ReadAsStringAsync());
        Assert.Equal("Updated title", updated.RootElement.GetProperty("title").GetString());
    }

    [Fact]
    public async Task Put_NonExistentId_Returns404()
    {
        var response = await _client.PutAsJsonAsync($"/api/tasks/{NonExistentId}", new { Title = "Updated title" });

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }

    [Fact]
    public async Task Delete_ExistingId_Returns204()
    {
        var createResponse = await _client.PostAsJsonAsync("/api/tasks", new { Title = "Task to delete" });
        using var created = JsonDocument.Parse(await createResponse.Content.ReadAsStringAsync());
        var createdId = created.RootElement.GetProperty("id").GetInt32();

        var deleteResponse = await _client.DeleteAsync($"/api/tasks/{createdId}");

        Assert.Equal(HttpStatusCode.NoContent, deleteResponse.StatusCode);

        var getResponse = await _client.GetAsync($"/api/tasks/{createdId}");
        Assert.Equal(HttpStatusCode.NotFound, getResponse.StatusCode);
    }

    [Fact]
    public async Task Delete_NonExistentId_Returns404()
    {
        var response = await _client.DeleteAsync($"/api/tasks/{NonExistentId}");

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }

    public class ApiFactory : WebApplicationFactory<Program>
    {
        // In-memory SQLite keeps its schema only while this connection stays open,
        // so tests never touch the real taskmanagement.db file.
        private readonly SqliteConnection _connection = new("DataSource=:memory:");

        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            _connection.Open();

            builder.ConfigureServices(services =>
            {
                services.RemoveAll(typeof(DbContextOptions<AppDbContext>));
                services.AddDbContext<AppDbContext>(options => options.UseSqlite(_connection));
            });
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (disposing)
            {
                _connection.Dispose();
            }
        }
    }
}
